//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GdgShopDBEntity : DbContext
    {
        public GdgShopDBEntity()
            : base("name=GdgShopDBEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CategoriesT> CategoriesTs { get; set; }
        public virtual DbSet<FavoriteProduct> FavoriteProducts { get; set; }
        public virtual DbSet<ImageT> ImageTs { get; set; }
        public virtual DbSet<oldOrder> oldOrders { get; set; }
        public virtual DbSet<OrderT> OrderTs { get; set; }
        public virtual DbSet<ProdectT> ProdectTs { get; set; }
        public virtual DbSet<UserT> UserTs { get; set; }
        public virtual DbSet<vWCart> vWCarts { get; set; }
        public virtual DbSet<vWCategorieByImage> vWCategorieByImages { get; set; }
        public virtual DbSet<vWFavoriteProduct> vWFavoriteProducts { get; set; }
        public virtual DbSet<vWImageTByProdectT> vWImageTByProdectTs { get; set; }
        public virtual DbSet<vWOrderTByProdectTAndUserT> vWOrderTByProdectTAndUserTs { get; set; }
        public virtual DbSet<vWProdectTByCategorieT> vWProdectTByCategorieTs { get; set; }
    }
}
