//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWProdectTByCategorieT
    {
        public string ProdectName { get; set; }
        public string ProdectNameAR { get; set; }
        public string Descriotion { get; set; }
        public string DescriotionAR { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> ProductsAvailableNum { get; set; }
        public string CategorieName { get; set; }
        public string CategorieNameAR { get; set; }
        public int CategorieID { get; set; }
        public int ProdectID { get; set; }

    }
}
