//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWOrderTByProdectTAndUserT
    {
        public string ProdectName { get; set; }
        public string ProdectNameAR { get; set; }
        public string Descriotion { get; set; }
        public string DescriotionAR { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> ProductsAvailableNum { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
    }
}
